# Trying Workflows and Actions
name: Compile with Pandoc

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://dang42/pandoc-ieee
        with:
          args: |>  # allows you to break string into multiple lines
            --standalone
            --filter=pandoc-citeproc
            --filter=Template/tablefilter.py
            --templat=Template/ieee.latex
            --output=output.pdf
            ExamplePaper.md
