# Trying Workflows and Actions
name: Compile with Pandoc

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://dang42/pandoc-ieee
        with:
          args: pandoc -o testing.html README.md


          #entrypoint: script.sh
          #args: --filter=pandoc-citeproc --filter=Template/tablefilter.py --template=Template/ieee.latex --output=output.pdf ExamplePaper.md
