# Trying Workflows and Actions
name: Compile with Pandoc

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - run: mkdir output
      - name: Build Documents
        uses: docker://dang42/pandoc-ieee
        with:
          args: "--filter=pandoc-citeproc --filter=templates/tablefilter.py --template templates/ieee.latex -o output/output.pdf ExamplePaper.md"
      - name: Commit Files #Save the files
        run: |
          git config --local user.name "djgoldsmith"
          git add ./output
          git commit -m "Commit Built paper"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      
      
      # -- This Stores as an Artifact (But not in the Repo)
      #- uses: actions/upload-artifact@master
      #  with:
      #    name: output
      #    path: output


#args: --filter=pandoc-citeproc --filter=Template/tablefilter.py --template=Template/ieee.latex --output=output.pdf ExamplePaper.md
