# Trying Workflows and Actions
name: Compile with Pandoc

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: mkdir output
      - name: Build Documents
        uses: docker://dang42/pandoc-ieee
        with:
          args: "--filter=pandoc-citeproc --filter=templates/tablefilter.py --template/templates/ieee.latex -o output/output.pdf ExamplePaper.md"
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output


#args: --filter=pandoc-citeproc --filter=Template/tablefilter.py --template=Template/ieee.latex --output=output.pdf ExamplePaper.md
