# Trying Workflows and Actions
name: Compile with Pandoc

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: |
        mkdir output
      - uses: docker://dang42/pandoc-ieee
        with:
          args: "--filter=pandoc-citeproc --filter=templates/tablefilter.py ExamplePaper.md"

            #pandoc -o testREADME.md


          #entrypoint: script.sh
          #args: --filter=pandoc-citeproc --filter=Template/tablefilter.py --template=Template/ieee.latex --output=output.pdf ExamplePaper.md
